"""Upgraded Student model with grade_level and sponsor contact details

Revision ID: 89d8a5d0393f
Revises: b15d2283aa5f
Create Date: 2026-03-22 11:46:28.279394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d8a5d0393f'
down_revision = 'b15d2283aa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('grade_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sponsor_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sponsor_relation', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sponsor_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sponsor_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('enrollment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('students_admission_number_key', type_='unique')
        batch_op.drop_constraint('students_nemis_upi_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_grade_level'), ['grade_level'], unique=False)
        batch_op.drop_column('nemis_upi')
        batch_op.drop_column('full_name')
        batch_op.drop_column('current_balance')
        batch_op.drop_column('parent_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nemis_upi', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_students_grade_level'))
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))
        batch_op.create_unique_constraint('students_nemis_upi_key', ['nemis_upi'])
        batch_op.create_unique_constraint('students_admission_number_key', ['admission_number'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('sponsor_email')
        batch_op.drop_column('sponsor_phone')
        batch_op.drop_column('sponsor_relation')
        batch_op.drop_column('sponsor_name')
        batch_op.drop_column('grade_level')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
