"""Added Student master table and linked to ledger

Revision ID: b15d2283aa5f
Revises: c30f178b1336
Create Date: 2026-03-22 11:38:31.175563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b15d2283aa5f'
down_revision = 'c30f178b1336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_ledgers', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False,
               postgresql_using='student_id::uuid')
        batch_op.drop_index('ix_student_ledgers_student_id')
        batch_op.create_foreign_key('fk_student_ledgers_student_id_students', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_ledgers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_ledgers_student_id_students', type_='foreignkey')
        batch_op.create_index('ix_student_ledgers_student_id', ['student_id'], unique=False)
        batch_op.alter_column('student_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='student_id::text')

    # ### end Alembic commands ###
