"""Added FeeStructure and StudentLedger tables

Revision ID: c30f178b1336
Revises: 1f9e0c20b331
Create Date: 2026-03-21 20:20:36.360253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30f178b1336'
down_revision = '1f9e0c20b331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('target_cohort', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    with op.batch_alter_table('student_ledgers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_ledgers_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_ledgers_student_id'))

    op.drop_table('student_ledgers')
    op.drop_table('fee_structures')
    # ### end Alembic commands ###
